stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - pi
  image: docker:cli
  before_script:
    - apk add --no-cache rsync docker-compose
  script:
    - rsync -a --delete --exclude='.git' --exclude='audiobookshelf/config' --exclude='audiobookshelf/metadata' --exclude='audiobookshelf/podcasts' --exclude='burgen/.venv' --exclude='burgen/data' --exclude='burgen/site' --exclude='gitlab-runner' "$CI_PROJECT_DIR/" /infrastructure/
    - cd /infrastructure
    - docker compose pull --ignore-buildable
    - docker compose build
    - docker compose up -d --remove-orphans
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
