services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /home/wilcomb/.cloudflared:/home/nonroot/.cloudflared:ro
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    depends_on:
      - audiobookshelf

  burgen:
    build: ./burgen
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    volumes:
      - /home/wilcomb/gdrive:/audiobooks
      - ./audiobookshelf/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Berlin
